### ISSUE TITLE
Error When Importing

### ISSUE THREAD

**Issue by RafilAlArs** [Riron/ionic-img-viewer#55] opened 2017-05-05 11:17 UTC
Hi 
I follow the installation instruction and I got this error when trying to import it can you help to solve this issue.
my project is ionic 2, the import statement is
import { IonicImageViewerModule } from 'ionic-img-viewer';
the Error that I got.

Typescript Error
Type 'any' is not a constructor function type.
node_modules/ionic-img-viewer/dist/src/image-viewer-transition-gesture.d.ts
import { DomController } from 'ionic-angular';
export declare class ImageViewerTransitionGesture extends PanGesture {
    private component;

**Comment by Riron** [comment] 2017-05-05 15:54
Probably a duplicate of #51

**Closed** 2017-05-05 15:57 UTC
