### ISSUE TITLE
Double tap on the pic when open to zoom not work

### ISSUE THREAD

**Issue by kadox07** [Riron/ionic-img-viewer#10] opened 2016-10-21 11:12 UTC
This feature: Double tap on the pic when open to zoom Not worked! Fix it

**Comment by Riron** [comment] 2016-10-23 18:55
Probably duplicate of #5 
If not, could you please elaborate ? What device ? What conditions ?

And try the 1.1.2 release, it may fix your problem.

**Comment by Riron** [comment] 2016-11-06 16:13
I suppose the 1.1.2 release did it, closing for now.

**Closed by Riron** 2016-11-06 16:13 UTC
Labels: bug, duplicate
