### ISSUE TITLE
Doesn't work with new version of ionic

### ISSUE THREAD

**Issue by filippodicostanzo** [Riron/ionic-img-viewer#90] opened 2017-10-01 12:23 UTC
### Please provide you version information :
Dependency      |Version
----------------|-------
ionic2          |  3.7.1
angular         | 4.4.3
ionic-img-viewer| 2.6.1

### Have you checked...
- [X] That npm install returns no warning ?
- [ ] Doing a purge of your node_modules folder ?

After i updated the newest version of ionic Ionic Img Viewer doesn't work correctly.

When i clicked on image the class change in active but doesn't work!

**Comment by sharkoz** [comment] 2017-10-02 13:43
Hi,

I have the same config as yours and it's working for me...

Maybe check that you are correctly setup.

**Comment by filippodicostanzo** [comment] 2017-10-02 13:47
Yes, the code is very simple :) 

I try with a new project of ionic for accurate testing and doesn't work.

Works with ionic serve but doesn't work on a iOS simualtor or iOS real device.

This is my code:

app.module.ts

`import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { IonicImageViewerModule } from 'ionic-img-viewer';

import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';
import { ListPage } from '../pages/list/list';

import { DateAnnotationPipe } from '../pipes/date-annotation/date-annotation';
import { FacebookDatePipe } from '../pipes/facebook-date/facebook-date';
import { InstagramDatePipe } from '../pipes/instagram-date/instagram-date';
import { StarsRatingPipe } from '../pipes/stars-rating/stars-rating';
import { NewLinePipe } from '../pipes/new-line/new-line';

import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';

@NgModule({
  declarations: [
    MyApp,
    HomePage,
    ListPage,

    DateAnnotationPipe,
    InstagramDatePipe,
    FacebookDatePipe,
    StarsRatingPipe,
    NewLinePipe
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp),
    IonicImageViewerModule
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage,
    ListPage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
export class AppModule {}
`

home.html

`<ion-header>
  <ion-navbar>
    <button ion-button menuToggle>
      <ion-icon name="menu"></ion-icon>
    </button>
    <ion-title>Home</ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
  <h3>Ionic Menu Starter</h3>

  <p>
    If you get lost, the <a href="http://ionicframework.com/docs/v2">docs</a> will show you the way.
  </p>

  <button ion-button secondary menuToggle>Toggle Menu</button>
  <img src="http://www.tg24.info/network/wp-content/uploads/2015/09/festa-dei-nonni-680x365_c.jpg" imageViewer>
</ion-content>
`

**Comment by claudiozam** [comment] 2017-10-03 21:00
Hi, i have the same issue. Works with ionic serve but doesn't work on a iOS simualtor or iOS real device.

Dependency | Version
-- | --
ionic2 | 3.7.1
angular | 4.4.3
ionic-img-viewer | 2.7.0
cordova ios | 4.5.1

Thanks.

**Comment by Riron** [comment] 2017-10-04 13:28
I see... problem is I don't have an iOS device so i cannot reproduce the bug.
Do you have any error in the console ?
Or maybe its a problem related to the styles (CSS) ?

Any help would be appreciated here...

**Comment by falcon8823** [comment] 2017-10-07 08:28
I face same problem if I build `--prod` only (not only iOS, but also browser and Android).
It seems to not included CSS file of ionic-img-viewer.

I work around this for copying the scss file into app.scss of app.

https://github.com/Riron/ionic-img-viewer/blob/master/src/image-viewer.scss

I guess the current changing of ionic-app-scripts(3.0.0) might cause this problem.
I faced other CSS problem on ionic-app-scripts(3.0.0) and ionic(3.7.1).

**Comment by Riron** [comment] 2017-10-07 12:13
Thanks for you help, yes it's certainly what causes the problem. I'll have a look at what changed in order to fix it and push a fix as soon as possible.

Meanwhile, you guys can use @falcon8823 workaround.

**Comment by ravi-pandit14** [comment] 2017-10-09 07:35
I found the problem (only run as a directive)

**Comment by Riron** [comment] 2017-10-10 17:40
I just released version `2.7.2` that should fix the problem.
Please upgrade and try again. Thanks !

**Comment by Riron** [comment] 2017-10-13 15:48
Please try the latest release, `2.7.3`.
This problem should be fixed has I now inlined the styles into the component. The styles won't be dependent of the build system anymore !

**Closed** 2017-10-14 09:16 UTC
Labels: bug

**Comment by falcon8823** [comment] 2017-10-18 12:43
I have confirmed the latest release works well!

Thanks @Riron.

**Comment by derman10** [comment] 2019-04-10 01:36
this plugin dont work anymore.
