### ISSUE TITLE
The plugin doesn't works with Android 4.4 version.

### ISSUE THREAD

**Issue by Mimicx** [Riron/ionic-img-viewer#5] opened 2016-10-09 22:43 UTC
Hi guys, i have a little problem, its that i have been testing the plugin with Android 4.4 version and the  double tap in the image to open the zoom doesn't works, but with the 6.0 android version it works ok.

**Comment by Riron** [comment] 2016-10-15 17:24
Hi,
Thanks for opening a issue. :+1: 
I havent tried the plugin on Android 4.4 unfortunately, only 5.0 and higher.

Are you using Crosswalk on Android 4.4 or the classic Android webview ? And is the rest of the plugin working fine ?
The problem is probably related to the 300ms tap delay on old mobile browsers. For many years, mobile browsers applied a 300-350ms delay between touchend and click while they waited to see if this was going to be a double-tap or not. It's not the case anymore so double tap is handled differently in the plugin.
If that's the right guess, the fix should be easy. :ok_hand: 
I'll try to have a look at it this week and keep you updated.

**Comment by Riron** [comment] 2016-11-06 16:11
Should be fixed by #e805b2ffb54918aab9ccb87250a47d5310048898

**Closed by Riron** 2016-11-06 16:11 UTC
Labels: bug
