### ISSUE TITLE
Enable swiping inside image viewer

### ISSUE THREAD

**Issue by dorinafilova94** [Riron/ionic-img-viewer#106] opened 2017-12-06 09:43 UTC
Hello,

I have an ion slides image gallery where each image is opened with imageViewer directive.
Is it possible to implement swiping left or right after the image is opened with the plugin?

**Comment by Riron** [comment] 2018-01-10 16:33
Duplicate of https://github.com/Riron/ionic-img-viewer/issues/2

**Closed by Riron** 2018-01-10 16:33 UTC
