### ISSUE TITLE
Production build

### ISSUE THREAD

**Issue by supergose** [Riron/ionic-img-viewer#38] opened 2017-03-23 21:39 UTC
when i try to build in production mode a get this error:

**> ionic build android --prod**

ionic-app-scripts build "--prod"

[22:22:55]  ionic-app-scripts 1.1.3 
[22:22:55]  build prod started ... 
[22:22:55]  clean started ... 
[22:22:55]  clean finished in 2 ms 
[22:22:55]  copy started ... 
[22:22:55]  ngc started ... 
can't resolve module /Users/user/Develop/vvCremaIonic/ionic2/vvApp/node_modules/ionic-img-viewer/node_modules/@angular/core/src/di/reflective_key.d.ts from /Users/user/Develop/vvCremaIonic/ionic2/vvApp/node_modules/ionic-img-viewer/node_modules/@angular/core/src/di/reflective_key.d.ts
[22:22:59]  build prod failed: can't find symbol KeyRegistry exported from module 
            /Users/user/Develop/vvCremaIonic/ionic2/vvApp/node_modules/ionic-img-viewer/node_modules/@angular/core/src/di/reflective_key.d.ts
[22:22:59]  ionic-app-script task: "build" 
[22:22:59]  Error: can't find symbol KeyRegistry exported from module 
            /Users/user/Develop/vvCremaIonic/ionic2/vvApp/node_modules/ionic-img-viewer/node_modules/@angular/core/src/di/reflective_key.d.ts
Error: can't find symbol KeyRegistry exported from module /Users/user/Develop/vvCremaIonic/ionic2/vvApp/node_modules/ionic-img-viewer/node_modules/@angular/core/src/di/reflective_key.d.ts
    at ReflectorHost.findDeclaration (/Users/user/Develop/vvCremaIonic/ionic2/vvApp/node_modules/@angular/compiler-cli/src/reflector_host.js:173:23)
    at /Users/user/Develop/vvCremaIonic/ionic2/vvApp/node_modules/@angular/compiler-cli/src/codegen.js:137:46
    at Array.forEach (native)
    at extractProgramSymbols (/Users/user/Develop/vvCremaIonic/ionic2/vvApp/node_modules/@angular/compiler-cli/src/codegen.js:120:10)
    at CodeGenerator.codegen (/Users/user/Develop/vvCremaIonic/ionic2/vvApp/node_modules/@angular/compiler-cli/src/codegen.js:57:29)
    at Object.runCodegen (/Users/user/Develop/vvCremaIonic/ionic2/vvApp/node_modules/@ionic/app-scripts/dist/aot/codegen/codegen-ng22.js:15:26)
    at Object.doCodegen (/Users/user/Develop/vvCremaIonic/ionic2/vvApp/node_modules/@ionic/app-scripts/dist/aot/codegen.js:6:31)
    at /Users/user/Develop/vvCremaIonic/ionic2/vvApp/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:41:30

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ionic:build" "--" "--prod"
npm ERR! node v7.7.1
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vvapp@ ionic:build: `ionic-app-scripts build "--prod"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vvapp@ ionic:build script 'ionic-app-scripts build "--prod"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vvapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build "--prod"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vvapp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vvapp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/.npm/_logs/2017-03-23T21_22_59_438Z-debug.log

**Comment by supergose** [comment] 2017-03-23 22:03
my package.json:

  "dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/platform-server": "2.4.8",
    "@ionic/storage": "2.0.0",
    "ionic-angular": "2.3.1",
    "ionic-img-viewer": "^1.3.0",
    "ionic-native": "3.1.0",
    "ionicons": "3.0.0",
    "rxjs": "5.0.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.1.4",
    "typescript": "2.0.9"
  },

**Comment by bonoadil** [comment] 2017-03-26 08:42
Hello, Have the same issue any news ?

**Comment by Riron** [comment] 2017-03-27 14:04
`"ionic-angular": "2.3.1"`  => is it even released yet ? I'm not sure.
There might be an issue with `v2.3.0` (released just a few days ago), I will try later on today.

Thanks for opening an issue

**Comment by Riron** [comment] 2017-03-31 09:57
Probably a duplicate of #41 - closing it as no info.

**Closed by Riron** 2017-03-31 09:57 UTC
