### ISSUE TITLE
Ionic 2 RC 2 Bug

### ISSUE THREAD

**Issue by danielehrhardt** [Riron/ionic-img-viewer#13] opened 2016-11-04 20:13 UTC
![image](https://cloud.githubusercontent.com/assets/19570043/20020845/8bb3e61c-a2d3-11e6-8687-d09d4e796671.png)
Uncaught Error: Unexpected value 'IonicImageViewerModule' imported by the module 'AppModule'(…)

**Comment by Riron** [comment] 2016-11-06 16:10
Duplicate of #9

**Closed by Riron** 2016-11-06 16:10 UTC
