### ISSUE TITLE
Metadata version mismatch for module version 4, expected 3

### ISSUE THREAD

**Issue by JeronimoNadalRuiz** [Riron/ionic-img-viewer#109] opened 2018-01-18 16:32 UTC
### Please provide you version information :
Dependency      |Version
----------------|-------
ionic2          | 3.19.1
angular         |4.1.0
ionic-img-viewer| 2.9.0

### Have you checked...
- [ ] That npm install returns no warning ?
- [ ] Doing a purge of your node_modules folder ?

When i build app, the cli return

Metadata version mismatch for module version 4, expected 3

Please, help me.

Thanks

**Comment by Riron** [comment] 2018-01-19 08:24
Duplicate of https://github.com/Riron/ionic-img-viewer/issues/103
Bottom line is use `angular@5`

**Closed as completed by Riron** 2018-01-19 08:24 UTC
